hint1: ['HP1','who','White']
hint2: ['HP1','what','Candlestick']
hint3: ['HP1','where','Study']
hint4: ['HP2','who','Scarlett']
hint5: ['HP2','who','Green']
hint6: ['HP2','what','Rope']
hint7: ['HP3','who','Green']
hint8: ['HP3','what','Lead Pipe']
hint9: ['HP3','where',Conservatory']
hint10: ['HP4','where','Kitchen']
hint11: ['HP4','where','Lounge']
hint12: ['HP4','what','Wrench']
hint13: ['HP5','who','Green']
hint14: ['HP5','what','Lead Pipe']
hint15: ['HP6','who','Peacock']
hint16: ['HP6','where','Lounge']
hint17: ['HP6','where','Dining Room']





