hint1: ['HP1','where','Hall']   
hint2: ['HP1','who','Plum']
hint3: ['HP1','what','Rope']
hint4: ['HP2','what','Wrench']
hint5: ['HP2','wha','Dagger']
hint6: ['HP2','where','Library']
hint7: ['HP3','where','Conservatory']   
hint8: ['HP3','who','Green']
hint9: ['HP11','who','Plum']
hint10: ['HP4','what','Lead Pipe']
hint11: ['HP4','who','Peacock']
hint12: ['HP4','where','Lounge']
hint13: ['HP5','where','Dining Room']
hint14: ['HP5','what','Rope']
hint15: ['HP6','who','White']
hint16: ['HP6','what','Candlestick']
hint17: ['HP6','where','Study']
hint18: ['HP7','who','Scarlett']
hint19: ['HP7','who','Green']
hint20: ['HP7','what','Rope']
hint21: ['HP8','who',Peacock']
hint22: ['HP8','what','Wrench']
hint23: ['HP9','who','Green']
hint24: ['HP9','what','Lead Pipe']
hint25: ['HP9','where',Conservatory']
hint26: ['HP10','where','Kitchen']
hint27: ['HP10','where','Lounge']
hint28: ['HP10','what','Wrench']






